# Currency Unit Code Generation for Compile-Time Evaluation
# 
# This module provides compile-time code generation for currency units
# to work around Julia's limitation that @dimension and @refunit must
# be evaluated at top level.

using Unitful
using Dates

"""
    generate_currency_units_file(unit_defs::Vector{UnitDefinition}, output_path::String)

Generate a Julia source file that defines currency units at top level.
This file can be included at compile time to properly register currency dimensions.

# Arguments
- `unit_defs`: Vector of UnitDefinition structs from taxonomy
- `output_path`: Path where to write the generated file

# Example
```julia
unit_defs = extract_units_from_taxonomy(objects)
generate_currency_units_file(unit_defs, "src/julia/generated_units.jl")
include("src/julia/generated_units.jl")
```
"""
function generate_currency_units_file(unit_defs::Vector{UnitDefinition}, output_path::String)
    io = IOBuffer()
    
    # File header
    println(io, "# Auto-generated currency unit definitions")
    println(io, "# Generated at: ", now())
    println(io, "# DO NOT EDIT - This file is automatically generated")
    println(io)
    println(io, "using Unitful")
    println(io, "using Unitful: @dimension, @refunit, @unit")
    println(io)
    
    # Separate currencies from other units
    currencies = filter(u -> u.category == "Currency", unit_defs)
    other_units = filter(u -> u.category != "Currency", unit_defs)
    
    # Generate currency dimensions and units
    if !isempty(currencies)
        println(io, "# Currency Dimensions")
        println(io, "# Each currency gets its own dimension to prevent mixing")
        println(io)
        
        for currency in currencies
            name = currency.name
            
            # Generate dimension
            println(io, "# Dimension for $name")
            # @dimension syntax: symb abbr name tf
            # Creates a dimension symbol (e.g., 𝐋 for Length)
            println(io, "@dimension $(name)Dim \"$(name)\" $(name)Dimension true")
            println(io)
            
            # Generate reference unit
            println(io, "# Reference unit for $name")
            # @refunit syntax: symb abbr name dimension tf [autodocs]
            # symb: the unit symbol (EUR)
            # abbr: the abbreviation string ("EUR")
            # name: the unit type name (EURUnit)
            # dimension: the dimension symbol (EURDim, not EURDimension)
            # tf: whether it's a base unit (true for base, false for derived)
            println(io, "@refunit $name \"$name\" $(name)Unit $(name)Dim true")
            println(io)
        end
        println(io)
    end
    
    # Generate other unit types (percentages, durations, etc.)
    if !isempty(other_units)
        println(io, "# Other Unit Types")
        println(io, "# These use existing Unitful dimensions")
        println(io)
        
        for unit in other_units
            name = unit.name
            category = unit.category
            
            # Map unit types to Unitful dimensions
            if category == "Percentage"
                println(io, "# Percentage is dimensionless")
                println(io, "const $name = Unitful.NoUnits")
            elseif category == "Duration"
                # Map to Unitful time dimension
                if name == "Années" || name == "Years"
                    println(io, "# Duration in years")
                    println(io, "const $name = 365.25u\"d\"  # Average year length")
                else
                    println(io, "# Duration: $name")
                    println(io, "# TODO: Map to appropriate Unitful time unit")
                end
            else
                println(io, "# Unknown unit type: $category for $name")
                println(io, "# Treating as dimensionless")
                println(io, "const $name = Unitful.NoUnits")
            end
            println(io)
        end
    end
    
    # Export all units
    println(io, "# Export all defined units")
    print(io, "export ")
    exported_names = [u.name for u in unit_defs]
    println(io, join(exported_names, ", "))
    println(io)
    
    # Write to file
    write(output_path, String(take!(io)))
    
    println("✓ Generated currency units file: $output_path")
    println("  - $(length(currencies)) currency dimension(s)")
    println("  - $(length(other_units)) other unit(s)")
    println()
    println("To use: include(\"$output_path\") at top level of your module")
end

"""
    generate_and_load_currency_units(unit_defs::Vector{UnitDefinition})

Generate currency units file and load it dynamically.
This is a convenience function that generates the file in a temporary location
and includes it.

Note: This still requires the include to happen at top level, so this function
should be called from module initialization code, not from within functions.

# Arguments
- `unit_defs`: Vector of UnitDefinition structs from taxonomy

# Returns
- Path to the generated file
"""
function generate_and_load_currency_units(unit_defs::Vector{UnitDefinition})
    # Generate in src/julia directory
    output_path = joinpath(@__DIR__, "generated_units.jl")
    generate_currency_units_file(unit_defs, output_path)
    return output_path
end

"""
    precompile_currency_units(taxonomy_path::String)

Pre-compile currency units from a taxonomy file.
This should be run as a build step before the main application starts.

# Arguments
- `taxonomy_path`: Path to OpenNorm document with Object Taxonomy

# Example
```bash
julia -e 'include("src/julia/currency_codegen.jl"); precompile_currency_units("documents/articles/CGI.Art.156.opennorm.md")'
```
"""
function precompile_currency_units(taxonomy_path::String)
    # This would need to parse the document to extract units
    # For now, just document the intended usage
    println("Precompiling currency units from: $taxonomy_path")
    println("This feature requires integration with the parser.")
    println("Use generate_currency_units_file() directly with extracted units.")
end
