# Auto-generated currency unit definitions
# Generated at: 2026-05-12T16:15:41.510
# DO NOT EDIT - This file is automatically generated

using Unitful
using Unitful: @dimension, @refunit, @unit

# Currency Dimensions
# Each currency gets its own dimension to prevent mixing

# Dimension for EUR
@dimension EURDim "EUR" EURDimension true

# Reference unit for EUR
@refunit EUR "EUR" EURUnit EURDim true

# Dimension for USD
@dimension USDDim "USD" USDDimension true

# Reference unit for USD
@refunit USD "USD" USDUnit USDDim true


# Export all defined units
export EUR, USD

