using CommonMark    # markdown parsing (needed by parser.jl)
using AbstractTrees # needed by structures.jl
using Z3            # SMT solving (needed by SMT_solver.jl)
using Unitful       # dimensional analysis (needed by unit_system.jl)

# Include generated currency units at top level (required for @dimension/@refunit macros)
# Only include if the file exists (it's generated by generate_currency_units.jl)
const GENERATED_UNITS_PATH = joinpath(@__DIR__, "generated_currency_units.jl")
if isfile(GENERATED_UNITS_PATH)
    include(GENERATED_UNITS_PATH)
end

include(joinpath(@__DIR__, "exceptions.jl"))
include(joinpath(@__DIR__, "structures.jl"))
include(joinpath(@__DIR__, "unit_system.jl"))
include(joinpath(@__DIR__, "type_checker.jl"))
include(joinpath(@__DIR__, "currency_codegen.jl"))
include(joinpath(@__DIR__, "parser.jl"))
include(joinpath(@__DIR__, "SMT_solver.jl"))

# Helper function to count taxons in a taxonomy tree
function count_taxons(taxon::Taxon{T}) where {T<:TaxonomyEnum}
    if isempty(taxon.name)
        return 0
    end
    count = 1
    for child in taxon.children
        count += count_taxons(child)
    end
    return count
end

# Helper function to count taxons at a specific depth (0 = root level children)
function count_taxons_at_depth(taxon::Taxon{T}, target_depth::Int, current_depth::Int=0) where {T<:TaxonomyEnum}
    if isempty(taxon.name)
        # Root node, count its children
        count = 0
        for child in taxon.children
            count += count_taxons_at_depth(child, target_depth, 0)
        end
        return count
    end
    
    if current_depth == target_depth
        return 1
    end
    
    count = 0
    for child in taxon.children
        count += count_taxons_at_depth(child, target_depth, current_depth + 1)
    end
    return count
end

# Helper function to count taxons under a specific named parent
function count_taxons_under(taxon::Taxon{T}, parent_name::String) where {T<:TaxonomyEnum}
    if taxon.name == parent_name
        # Found the parent, count its children recursively
        return count_taxons(taxon)
    end
    
    # Search in children
    count = 0
    for child in taxon.children
        count += count_taxons_under(child, parent_name)
    end
    return count
end

# Helper function to count taxons by source (local vs imported)
function count_taxons_by_source(taxon::Taxon{T}, base_package::String) where {T<:TaxonomyEnum}
    local_count = 0
    imported_count = 0
    
    function count_recursive(node::Taxon{T})
        if !isempty(node.name)
            if node.source == base_package
                local_count += 1
            else
                imported_count += 1
            end
        end
        for child in node.children
            count_recursive(child)
        end
    end
    
    count_recursive(taxon)
    return (local_count, imported_count)
end

# Helper function to count taxons by source under a specific named parent
function count_taxons_by_source_under(taxon::Taxon{T}, parent_name::String, base_package::String) where {T<:TaxonomyEnum}
    # Find the parent node first
    function find_parent(node::Taxon{T})
        if node.name == parent_name
            return node
        end
        for child in node.children
            result = find_parent(child)
            if result !== nothing
                return result
            end
        end
        return nothing
    end
    
    parent_node = find_parent(taxon)
    if parent_node === nothing
        return (0, 0)  # Parent not found
    end
    
    # Count by source under this parent
    local_count = 0
    imported_count = 0
    
    function count_recursive(node::Taxon{T})
        if !isempty(node.name)
            if node.source == base_package
                local_count += 1
            else
                imported_count += 1
            end
        end
        for child in node.children
            count_recursive(child)
        end
    end
    
    count_recursive(parent_node)
    return (local_count, imported_count)
end

function validate_document(path::String)
    """
    Parse and validate an OpenNorm document using SMT solver.
    Returns (document, solver, result) or nothing on error.
    """
    # Parse the document
    println("Parsing document: $path")

    local document
    try
        document = parse_document(path)
    catch e
        if e isa OpenNormException
            showerror(stdout, e)
            println()
            return nothing
        else
            rethrow(e)
        end
    end

    # Display document info
    println("\n=== Document Info ===")
    println("Title: ", document.manifest.title)
    println("Package: ", document.manifest.package)
    println("Version: ", document.manifest.version)
    println("Imports: ", length(document.manifest.imports), " document(s)")

    # Count norms from this document vs imported
    local_norms  = filter(n -> n.package == document.manifest.package, document.norms)
    imported_norms = filter(n -> n.package != document.manifest.package, document.norms)

    # Count taxonomy entities
    println("\n=== Taxonomy Info ===")
    println("Norms: ", length(document.norms), " (", length(imported_norms), " imported, ", length(local_norms), " local)")
    total_entities = count_taxons(document.entityTaxonomy)
    total_roles    = count_taxons(document.actorTaxonomy)
    total_actions  = count_taxons(document.actionTaxonomy)
    total_objects  = count_taxons(document.objectTaxonomy)
    
    # Count by source (local vs imported)
    local_entities, imported_entities = count_taxons_by_source(document.entityTaxonomy, document.manifest.package)
    local_roles, imported_roles = count_taxons_by_source(document.actorTaxonomy, document.manifest.package)
    local_actions, imported_actions = count_taxons_by_source(document.actionTaxonomy, document.manifest.package)
    local_objects, imported_objects = count_taxons_by_source(document.objectTaxonomy, document.manifest.package)

    println("Entity taxonomy: ", total_entities, " entities (", imported_entities, " imported, ", local_entities, " local)")
    println("Role taxonomy:   ", total_roles,    " roles (", imported_roles, " imported, ", local_roles, " local)")
    println("Action taxonomy: ", total_actions,  " actions (", imported_actions, " imported, ", local_actions, " local)")
    println("Object taxonomy: ", total_objects,  " objects (", imported_objects, " imported, ", local_objects, " local)")
    
    # Count OpenNormVariables breakdown with source tracking
    if total_objects > 0
        # Count Constants
        local_constants, imported_constants = count_taxons_by_source_under(document.objectTaxonomy, "Constants", document.manifest.package)
        total_constants = local_constants + imported_constants
        
        # Count Parameters
        local_parameters, imported_parameters = count_taxons_by_source_under(document.objectTaxonomy, "Parameters", document.manifest.package)
        total_parameters = local_parameters + imported_parameters
        
        # Count ComputedVariables
        local_computed, imported_computed = count_taxons_by_source_under(document.objectTaxonomy, "ComputedVariables", document.manifest.package)
        total_computed = local_computed + imported_computed
        
        if total_constants > 0 || total_parameters > 0 || total_computed > 0
            println("  - Constants:        ", total_constants, " (", imported_constants, " imported, ", local_constants, " local)")
            println("  - Parameters:       ", total_parameters, " (", imported_parameters, " imported, ", local_parameters, " local)")
            println("  - ComputedVariables:", total_computed, " (", imported_computed, " imported, ", local_computed, " local)")
        end
    end

    # Perform dimensional analysis once on the merged document
    try
        println("\n=== Dimensional Analysis ===")
        unit_defs = extract_units_from_taxonomy(document.objectTaxonomy)
        if !isempty(unit_defs)
            println("Registering $(length(unit_defs)) units from taxonomy...")
            register_units!(unit_defs)
            
            # Build type environment from taxonomy
            println("Building type environment...")
            type_env = build_type_environment(document.objectTaxonomy)
            println("Type environment contains $(length(type_env)) typed variables")
            
            # Parse procedures from the main document and all imports
            println("Parsing procedures...")
            all_procedures = Procedure[]
            
            # Parse from main document
            parser = CommonMark.Parser()
            CommonMark.enable!(parser, CommonMark.FootnoteRule())
            ast = parser(read(path, String))
            main_procedures = parse_procedures(ast, path)
            append!(all_procedures, main_procedures)
            
            # Parse from each imported document
            if !isempty(document.manifest.imports)
                base_dir = dirname(path)
                for import_spec in document.manifest.imports
                    try
                        import_path, _ = resolve_import_path(import_spec, base_dir, pwd())
                        import_ast = parser(read(import_path, String))
                        import_procedures = parse_procedures(import_ast, import_path)
                        append!(all_procedures, import_procedures)
                    catch e
                        # Skip imports that can't be resolved (e.g., stdlib)
                        continue
                    end
                end
            end
            
            procedures = all_procedures
            
            if !isempty(procedures)
                println("Performing type resolution and validation for $(length(procedures)) procedures...")
                valid_count = 0
                error_count = 0
                
                for proc in procedures
                    # Type resolution phase: convert raw expression text to ExprNode AST
                    try
                        # Determine if this is a Case expression or simple assignment
                        is_case = startswith(proc.expression_text, "Case:") || 
                                 startswith(proc.expression_text, "CumulativeCase:")
                        
                        # Parse the expression text into an ExprNode AST
                        expression_ast = if is_case
                            parse_case_expression(proc.expression_text)
                        else
                            # Remove the assignment part and parse the right-hand side
                            rhs = replace(proc.expression_text, r"^\*[^*]+\*\s*=\s*" => "")
                            parse_expression_for_type_checking(strip(rhs))
                        end
                        
                        # Validate the parsed expression
                        validate_computed_variable(proc.name, expression_ast, type_env, proc.location)
                        println("  ✓ *$(proc.name)* (validated)")
                        valid_count += 1
                    catch e
                        if e isa DimensionalMismatchError
                            showerror(stderr, e)
                            println(stderr)
                            error_count += 1
                        else
                            # For other errors (e.g., parsing issues), show warning with details
                            println("  ⚠ *$(proc.name)* ($(typeof(e)): $(e))")
                            error_count += 1
                        end
                    end
                end
                
                if error_count > 0
                    println("⚠️  Dimensional analysis complete: $(valid_count) valid, $(error_count) errors")
                else
                    println("✓ Dimensional analysis complete: all $(valid_count) procedures validated successfully")
                end
            else
                println("No procedures found in operational layer")
                println("✓ Dimensional analysis setup complete (ready for procedure validation)")
            end
        else
            println("No units found in taxonomy, skipping dimensional analysis")
        end
    catch e
        if e isa DimensionalMismatchError
            showerror(stderr, e)
            println(stderr)
            println(stderr, "⚠️  Dimensional analysis failed.\n")
        else
            @warn "Error during dimensional analysis setup" exception=(e, catch_backtrace())
        end
    end
    
    # Check satisfiability
    println("\n=== Checking Satisfiability ===")
    println("Translating OpenNorm to SMT...")
    solver, contradictions = to_smt(document)
    println("Running Z3 SMT solver...")
    result = check(solver)

    result_str = string(result)
    if result_str == "sat"
        println("✓ Document is SATISFIABLE")
        println("  The ", length(document.norms), " norms are logically consistent — no contradictions found")
        println("  Z3 verified all norms can hold simultaneously")
    elseif result_str == "unsat"
        println("✗ Document is UNSATISFIABLE")

        if !isempty(contradictions)
            for contr in contradictions
                println("\n  ⚠️  CONTRADICTION DETECTED (Jural Opposites)")
                println("  ═══════════════════════════════════════════")
                println("  Norm 1: #$(contr.norm1_ref)")
                println("    $(contr.norm1_text)")
                println("    Position: $(contr.norm1_pos)")
                println()
                println("  Norm 2: #$(contr.norm2_ref)")
                println("    $(contr.norm2_text)")
                println("    Position: $(contr.norm2_pos)")
                println()
                println("  Explanation:")
                println("    $(contr.norm1_pos) and $(contr.norm2_pos) are Hohfeldian opposites.")
                println("    The norms are related through taxonomy subsumption:")
                println("      - $(contr.norm1_actor) ⊇ $(contr.norm2_actor)")
                println("      - $(contr.norm1_action) ⊇ $(contr.norm2_action)")
                println("      - $(contr.norm1_object) ⊇ $(contr.norm2_object)")
                println("    This creates a logical contradiction.")
            end
        end
    else
        println("? Satisfiability is UNKNOWN")
        println("  Z3 could not determine satisfiability")
        println("  (This may happen with complex constraints or timeouts)")
    end

    return (document, solver, result)
end

function opennorm(path::String)
    """
    Main entry point for OpenNorm validation.
    Returns true if the document is satisfiable, false otherwise.
    """
    result = validate_document(path)
    result === nothing && return false
    doc, solver, check_result = result
    return string(check_result) == "sat"
end

# Run on the CGI Article 156 document
is_valid = opennorm("./documents/articles/CGI.Art.156.md")
println("\n=== Final Result ===")
println(is_valid ? "✓ Document is valid" : "✗ Document has issues")