//! Stage 3: Transpiler — OpenNorm AST → Lean 4 source.
//!
//! For stdlib packages: Generate inductive types from taxonomies, then extract Lean code

use crate::ast::*;
use crate::error::OpenNormError;
use std::collections::HashMap;

pub fn transpile(doc: &Document, source_file: &str) -> Result<String, OpenNormError> {
    let mut out = String::new();

    emit_header(&mut out, source_file, &doc.manifest.package, &doc.manifest.version);
    
    // For stdlib packages, generate types and extract code
    if doc.manifest.package_type == PackageType::Stdlib {
        transpile_stdlib(doc, &mut out)?;
    } else {
        // Legacy document transpilation (not implemented yet)
        out.push_str("-- Legacy document transpilation not yet implemented\n");
    }

    Ok(out)
}


fn emit_header(out: &mut String, source: &str, package: &str, version: &str) {
    out.push_str(&format!(
        "/-\n\
         Auto-generated by OpenNorm from {source}\n\
         Source document is authoritative. Do not edit this file.\n\
         Package: {package} v{version}\n\
         -/\n\n"
    ));
}

fn transpile_stdlib(doc: &Document, out: &mut String) -> Result<(), OpenNormError> {
    // Generate inductive types from taxonomies
    if !doc.taxonomies.is_empty() {
        out.push_str("-- ══════════════════════════════════════════════════════════════════════════\n");
        out.push_str("-- TAXONOMIES (Generated Inductive Types)\n");
        out.push_str("-- ══════════════════════════════════════════════════════════════════════════\n\n");
        
        generate_taxonomies(doc, out)?;
    }
    
    // Extract code from Axioms section
    if let Some(axioms) = &doc.axioms {
        out.push_str("-- ══════════════════════════════════════════════════════════════════════════\n");
        out.push_str("-- AXIOMS\n");
        out.push_str("-- ══════════════════════════════════════════════════════════════════════════\n\n");
        
        for block in &axioms.code_blocks {
            if block.language.contains("lean") {
                out.push_str(&block.content);
                out.push('\n');
            }
        }
    }
    
    // Extract code from FormalDescription section
    if let Some(formal) = &doc.formal_description {
        out.push_str("-- ══════════════════════════════════════════════════════════════════════════\n");
        out.push_str("-- FORMAL DESCRIPTION\n");
        out.push_str("-- ══════════════════════════════════════════════════════════════════════════\n\n");
        
        for block in &formal.code_blocks {
            if block.language.contains("lean") {
                out.push_str(&block.content);
                out.push('\n');
            }
        }
    }
    
    Ok(())
}

fn generate_taxonomies(doc: &Document, out: &mut String) -> Result<(), OpenNormError> {
    for taxonomy in &doc.taxonomies {
        generate_taxonomy_inductive(&taxonomy, out)?;
        out.push('\n');
    }
    
    // Generate type aliases for convenience
    out.push_str("-- Type aliases for convenience\n");
    for taxonomy in &doc.taxonomies {
        let taxonomy_type = taxonomy.name.replace(" ", "");
        
        // Create aliases for top-level items in the taxonomy
        // For example: LegalQuantifiersTaxonomy_Quantifier -> Quantifier
        for item in &taxonomy.items {
            // Skip 'Position' alias as it's redefined in FormalDescription as a product type
            if item.name == "Position" {
                continue;
            }
            
            let full_type = format!("{}_{}", taxonomy_type, item.name);
            out.push_str(&format!("abbrev {} := {}\n", item.name, full_type));
            
            // Also create aliases for nested types that are commonly used
            generate_nested_type_aliases(&taxonomy_type, &item.name, &item.children, out);
        }
    }
    out.push('\n');
    
    Ok(())
}

fn generate_taxonomy_inductive(taxonomy: &Taxonomy, out: &mut String) -> Result<(), OpenNormError> {
    let taxonomy_type = taxonomy.name.replace(" ", "");
    
    // Generate flattened types with hierarchical names (deepest first)
    generate_flat_types_depth_first(&taxonomy_type, &taxonomy.items, "", out)?;
    
    // Generate main taxonomy type
    out.push_str(&format!("inductive {} where\n", taxonomy_type));
    for item in &taxonomy.items {
        if item.children.is_empty() {
            out.push_str(&format!("  | {} : {}\n", item.name, taxonomy_type));
        } else {
            let nested_type = format!("{}_{}",taxonomy_type, item.name);
            out.push_str(&format!("  | {} : {} → {}\n", item.name, nested_type, taxonomy_type));
        }
    }
    out.push_str("\n");
    
    Ok(())
}

fn generate_flat_types_depth_first(parent: &str, items: &[TaxonomyItem], prefix: &str, out: &mut String) -> Result<(), OpenNormError> {
    for item in items {
        if !item.children.is_empty() {
            let type_name = if prefix.is_empty() {
                format!("{}_{}", parent, item.name)
            } else {
                format!("{}_{}", prefix, item.name)
            };
            
            // Recursively generate child types FIRST (depth-first)
            generate_flat_types_depth_first(parent, &item.children, &type_name, out)?;
            
            // Then generate this type
            out.push_str(&format!("inductive {} where\n", type_name));
            for child in &item.children {
                if child.children.is_empty() {
                    out.push_str(&format!("  | {} : {}\n", child.name, type_name));
                } else {
                    let child_type = format!("{}_{}", type_name, child.name);
                    out.push_str(&format!("  | {} : {} → {}\n", child.name, child_type, type_name));
                }
            }
            out.push_str("  deriving BEq, DecidableEq, Repr\n");
            out.push_str("\n");
        }
    }
    Ok(())
}

fn generate_flat_types(parent: &str, items: &[TaxonomyItem], prefix: &str, out: &mut String) -> Result<(), OpenNormError> {
    for item in items {
        if !item.children.is_empty() {
            let type_name = if prefix.is_empty() {
                format!("{}_{}", parent, item.name)
            } else {
                format!("{}_{}", prefix, item.name)
            };
            
            out.push_str(&format!("inductive {} where\n", type_name));
            for child in &item.children {
                if child.children.is_empty() {
                    out.push_str(&format!("  | {} : {}\n", child.name, type_name));
                } else {
                    let child_type = format!("{}_{}", type_name, child.name);
                    out.push_str(&format!("  | {} : {} → {}\n", child.name, child_type, type_name));
                }
            }
            out.push_str("  deriving BEq, DecidableEq, Repr\n");
            out.push_str("\n");
            
            // Recursively generate child types
            generate_flat_types(parent, &item.children, &type_name, out)?;
        }
    }
    Ok(())
}

fn collect_nested_types(items: &[TaxonomyItem], nested_types: &mut Vec<(String, Vec<TaxonomyItem>)>) {
    for item in items {
        if !item.children.is_empty() {
            // This item has children, so it needs a nested type
            let type_name = format!("{}Type", item.name);
            nested_types.push((type_name, item.children.clone()));
            
            // Recursively collect nested types from children
            collect_nested_types(&item.children, nested_types);
        }
    }
}

fn generate_nested_type_aliases(taxonomy_type: &str, parent_name: &str, items: &[TaxonomyItem], out: &mut String) {
    // Generate aliases for commonly used nested types
    // For example: HohfeldianTaxonomy_Operator_Perspective -> Perspective
    // Only generate aliases for items that have children (i.e., are types, not constructors)
    for item in items {
        if !item.children.is_empty() {
            let full_type = format!("{}_{}_{}", taxonomy_type, parent_name, item.name);
            out.push_str(&format!("abbrev {} := {}\n", item.name, full_type));
            
            // Recursively handle deeper nesting
            let nested_parent = format!("{}_{}", parent_name, item.name);
            generate_nested_type_aliases(taxonomy_type, &nested_parent, &item.children, out);
        }
    }
}
