//! Stage 3: Transpiler — OpenNorm AST → Lean 4 source.
//!
//! The drafter never sees or edits this output. The .md source is authoritative.
//! Generated .lean files carry a header stating they are not to be edited.
//!
//! Mapping rules:
//!   § Grant     → MIT_Grant def + theorems
//!   § Obligations → obligation propositions
//!   § Waivers   → waiver propositions
//!   Fuzzy terms → sorry stubs (documented, not silent)
//!   Defeasible bullets → Rule list + winning_rule call

use crate::ast::*;
use crate::error::OpenNormError;

// ─────────────────────────────────────────────────────────────────────────────
// Public entry point
// ─────────────────────────────────────────────────────────────────────────────

pub fn transpile(doc: &Document, source_file: &str) -> Result<String, OpenNormError> {
    let mut out = String::new();

    emit_header(&mut out, source_file, &doc.id, &doc.version);
    emit_imports(&mut out);
    emit_actors_and_actions(&mut out, doc);
    emit_sections(&mut out, doc);
    emit_sorry_inventory(&mut out, doc);

    Ok(out)
}

// ─────────────────────────────────────────────────────────────────────────────
// Header
// ─────────────────────────────────────────────────────────────────────────────

fn emit_header(out: &mut String, source: &str, id: &str, version: &str) {
    out.push_str(&format!(
        "-- Auto-generated by OpenNorm 0.1 from {source}\n\
         -- Source document is authoritative. Do not edit this file.\n\
         -- Regenerate with: opennorm transpile {source}\n\
         -- Document: {id} v{version}\n\n"
    ));
}

fn emit_imports(out: &mut String) {
    out.push_str("import OpenNorm.Deontic\n\n");
}

// ─────────────────────────────────────────────────────────────────────────────
// Type declarations for document-specific actors and actions
// ─────────────────────────────────────────────────────────────────────────────

fn emit_actors_and_actions(out: &mut String, doc: &Document) {
    out.push_str("-- ── Document-specific types ────────────────────────────────────────────────\n");
    out.push_str("-- These are the concrete Actor and Action types for this document.\n\n");
    out.push_str("opaque Person   : Type\n");
    out.push_str("opaque Software : Type\n\n");
    out.push_str("-- Actions available for this license\n");

    // Collect all resolved terms from Grant section
    if let Some(grant) = doc.sections.iter().find(|s| s.kind == SectionKind::Grant) {
        let actions: Vec<&str> = grant.bullets.iter()
            .filter_map(|b| {
                if let Term::Resolved { name, .. } = &b.term {
                    Some(name.as_str())
                } else { None }
            })
            .collect();
        if !actions.is_empty() {
            out.push_str("inductive Action where\n");
            for action in &actions {
                let pascal = to_pascal_case(action);
                out.push_str(&format!("  | {pascal} : Software → Action\n"));
            }
            out.push('\n');
        }
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Section transpilation
// ─────────────────────────────────────────────────────────────────────────────

fn emit_sections(out: &mut String, doc: &Document) {
    for section in &doc.sections {
        match section.kind {
            SectionKind::Grant        => emit_grant(out, section, doc),
            SectionKind::Obligations  => emit_obligations(out, section),
            SectionKind::Waivers      => emit_waivers(out, section),
            SectionKind::Prohibitions => emit_prohibitions(out, section),
            _                         => {}
        }
    }
}

fn emit_grant(out: &mut String, section: &Section, doc: &Document) {
    out.push_str("-- ── § Grant ────────────────────────────────────────────────────────────────\n");

    // Main grant proposition
    out.push_str(&format!(
        "-- Transpiled from {} § Grant\n\
         def {}_Grant (recipient : Person) (sw : Software) : Prop :=\n\
           obtained recipient sw →\n",
        doc.id,
        sanitise_id(&doc.id)
    ));

    // Collect permitted actions from bullets
    let permitted: Vec<String> = section.bullets.iter()
        .filter_map(|b| {
            if let Term::Resolved { name, .. } = &b.term {
                Some(format!("  Permitted recipient (Action.{} sw)", to_pascal_case(name)))
            } else { None }
        })
        .collect();

    if permitted.is_empty() {
        out.push_str("  True -- no resolved actions found\n\n");
    } else {
        out.push_str(&permitted.join(" ∧\n"));
        out.push_str("\n\n");
    }

    // Sublicense bound theorem (universal, proved in Deontic.lean)
    out.push_str(&format!(
        "-- Sublicense bound: sublicensee cannot exceed licensor rights\n\
         -- Proved via sublicense_bound axiom in Deontic.lean\n\
         theorem {}_sublicense_bounded (r : Person) (sw : Software) :\n\
           {}_Grant r sw →\n\
           sublicense_rights r sw ⊆ original_rights sw := by\n\
           intro h\n\
           exact sublicense_bound _ _ _ (grant_rights_bounded h)\n\n",
        sanitise_id(&doc.id),
        sanitise_id(&doc.id),
    ));
}

fn emit_obligations(out: &mut String, section: &Section) {
    out.push_str("-- ── § Obligations ──────────────────────────────────────────────────────────\n");

    // Find the "Must include" bullet list
    for field in &section.fields {
        if field.label.to_lowercase().contains("when") {
            if let FieldValue::Single(Term::Resolved { name, .. }) = &field.value {
                out.push_str(&format!(
                    "-- Obligation triggered when: {name}\n"
                ));
            }
        }
    }

    out.push_str(
        "def notice_obligation (recipient : Person) (sw : Software) : Prop :=\n  \
         distributes_or_sublicenses recipient sw →\n    \
         includes_copyright_notice recipient sw ∧\n    \
         includes_permission_notice recipient sw\n\n"
    );

    // The substantial_portions fuzzy term becomes a sorry
    out.push_str(
        "-- Fuzzy term: substantial_portions\n\
         -- Declared in § Known Ambiguities. Human judgment required.\n\
         -- Review trigger: when contested in legal proceedings\n\
         def substantial_portions_threshold : Nat := by\n  \
         sorry -- documented: no threshold defined across 30 years of litigation\n\n"
    );
}

fn emit_waivers(out: &mut String, _section: &Section) {
    out.push_str("-- ── § Waivers ───────────────────────────────────────────────────────────────\n");
    out.push_str(
        "-- Warranty waiver: licensor waives all warranties\n\
         axiom warranty_waived (licensor : Person) (sw : Software) :\n  \
         ¬(Obligated licensor (Action.Warrant sw))\n\n\
         -- Liability waiver: licensor waives liability for all claims\n\
         axiom liability_waived (licensor : Person) (sw : Software) :\n  \
         ¬(Obligated licensor (Action.IndemnifyFor sw))\n\n\
         -- 'otherwise' fuzzy term: scope of liability waiver\n\
         -- Declared in § Known Ambiguities\n\
         def otherwise_scope : Prop := by\n  \
         sorry -- documented: catch-all, intentionally unbounded\n\n"
    );
}

fn emit_prohibitions(out: &mut String, section: &Section) {
    out.push_str("-- ── § Prohibitions ─────────────────────────────────────────────────────────\n");
    for bullet in &section.bullets {
        if let Term::Resolved { name, .. } = &bullet.term {
            let pascal = to_pascal_case(name);
            out.push_str(&format!(
                "axiom {name}_forbidden (a : Person) (sw : Software) :\n  \
                 Forbidden a (Action.{pascal} sw)\n\n"
            ));
        }
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Defeasibility: indented bullets → Rule list
// ─────────────────────────────────────────────────────────────────────────────

pub fn emit_defeasible_rules(out: &mut String, bullets: &[Bullet], field_name: &str) {
    if bullets.iter().any(|b| !b.sub_bullets.is_empty()) {
        let safe_name = sanitise_id(field_name);
        out.push_str(&format!(
            "-- Defeasible rules for field: {field_name}\n\
             def {safe_name}_rules : List (Rule Person Action) := [\n"
        ));
        emit_rule_list(out, bullets, 1);
        out.push_str("]\n\n");

        out.push_str(&format!(
            "def {safe_name}_permitted (p : Person) (a : Action) : Bool :=\n  \
             defeasible_permitted {safe_name}_rules p a\n\n"
        ));
    }
}

fn emit_rule_list(out: &mut String, bullets: &[Bullet], priority: usize) {
    for bullet in bullets {
        let name = sanitise_id(bullet.term.name());
        let permitted = match &bullet.term {
            Term::Resolved { .. } => "true",
            Term::Undefined(_)    => "true",
            Term::Fuzzy { .. }    => "true",  // fuzzy defaults to permitted with sorry
        };
        out.push_str(&format!(
            "  {{ id := \"{name}\", applies := fun p _ => {name} p, \
             permitted := {permitted}, priority := {priority} }},\n"
        ));
        if !bullet.sub_bullets.is_empty() {
            emit_rule_list(out, &bullet.sub_bullets, priority + 1);
        }
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Sorry inventory
// ─────────────────────────────────────────────────────────────────────────────

fn emit_sorry_inventory(out: &mut String, doc: &Document) {
    if doc.known_fuzzies.is_empty() { return; }

    out.push_str("-- ── Sorry inventory ────────────────────────────────────────────────────────\n");
    out.push_str("-- Every sorry in this file corresponds to a fuzzy term declared\n");
    out.push_str("-- in § Known Ambiguities. None are silent gaps.\n\n");

    out.push_str("def sorry_inventory : List (String × String) := [\n");
    for f in &doc.known_fuzzies {
        out.push_str(&format!(
            "  (\"{}\", \"{}\"),\n",
            f.name,
            f.review_trigger.replace('"', "'")
        ));
    }
    out.push_str("]\n");
}

// ─────────────────────────────────────────────────────────────────────────────
// Utility
// ─────────────────────────────────────────────────────────────────────────────

fn to_pascal_case(s: &str) -> String {
    s.split('_')
        .map(|w| {
            let mut c = w.chars();
            match c.next() {
                None    => String::new(),
                Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
            }
        })
        .collect()
}

fn sanitise_id(s: &str) -> String {
    s.chars()
        .map(|c| if c.is_alphanumeric() { c } else { '_' })
        .collect()
}